language: rust
rust:
  - stable
cache: cargo

env:
  - FEATURES=std
  - FEATURES=

script:
  - cargo build --all --verbose --no-default-features --features="$FEATURES"
  - cargo test --all --verbose --no-default-features --features="$FEATURES"
